### PR TITLE
Fix: default image sharpness

### LINKED ISSUE #276: Image appear to be unexpectedly sharpened
## Steps to reproduce

1. Load an image through CDN, with quality at 100% and sharpen either unset or at 0
2. Notice an increased sharpening of supplied jpg

Sample image:
 
blurb1

Original zoomed:

 
screen shot on 2017-11-01 at 14_55_33

CDN zoomed:
 
screen shot on 2017-11-01 at 14_55_22

### PR DESCRIPTION
**Pull request by adamkdean**
Fixes #276 

000498f fix: allow zero as sharpness param value
b2ffe24 fix: do not sharpen images by default

Old default:
image

New default:
image

Adding `sharpen=0` (same as default):
image

### CODE REVIEW

**Comment by adamkdean** [comment]
@mingard 

Sample picture:
image

Default old:
image

Default old zoomed:
image

Default new:
image

Default new zoomed:
image

**Comment by jimlambie** [comment]
@eduardoboucas are you happy with all this?

File: dadi/lib/handlers/image.js [hunk 1]
```diff
@@ -920,7 +920,10 @@ ImageHandler.prototype.sanitiseOptions = function (options) {
       if (options[key] !== '0' || settings[0].allowZero || settings[0].default) {
         if (options[key] !== '0' || settings[0].allowZero) {
           if (settings[0].lowercase) value = value.toLowerCase()
-          imageOptions[settings[0].name] = _.isFinite(value) ? parseFloat(value) : value
+          value = _.isFinite(value) ? parseFloat(value) : value
+          if (settings[0].minimumValue && value < settings[0].minimumValue) value = settings[0].minimumValue
```
Comment (eduardoboucas) [inline dadi/lib/handlers/image.js]: I find these two `if`/`else if` blocks a bit hard to read. Could we perhaps change it to:

```js
if (settings[0].minimumValue && value < settings[0].minimumValue) {
  value = settings[0].minimumValue
} else if (settings[0].maximumValue && value > settings[0].maximumValue) {
  value = settings[0].maximumValue
}
```

Comment (jimlambie) [reply dadi/lib/handlers/image.js]: @adamkdean over to you

Comment (adamkdean) [reply dadi/lib/handlers/image.js]: Sorry @eduardoboucas – I don't usually create blocks for single expressions. Fixed though in 33cf07a. @jimlambie 🚀 ?
