### PR TITLE
Use getStream to better handle missing cache file

### LINKED ISSUE #317: Missing key error when using routes
When using routes with or without conditions, an error is thrown:

Recipe:
```json
{
  "recipe": "thumbnail",
  "settings": {
    "format": "jpg",
    "quality": "70",
    "width": "400",
    "height": "400",
    "resizeStyle": "entropy"
  }
}
```

Route:
```json
{
  "route": "tile-thumb",
  "branches": [
    {
      "recipe": "thumbnail"
    }
  ]
}
```

Error: 
```json
{"message":"The specified key does not exist"}
```

Version: 2.0.0
Node version: 8.10.0
OS: linux

### PR DESCRIPTION
**Pull request by jimlambie**
This PR ensures that if the cache doesn't contain the requested key then it can continue to process the request, rather than returning the cache module's error to the end-user.

Fix #317

### CODE REVIEW

File: dadi/lib/models/route.js [hunk 1]
```diff
@@ -218,7 +218,7 @@ Route.prototype.getNetwork = function () {
 }
 
 Route.prototype.getRecipe = function () {
-  return cache.get(this._getCacheKey()).then((cachedRecipe) => {
+  return cache.getStream(this._getCacheKey()).then(cachedRecipe => {
     if (cachedRecipe) return Promise.resolve(cachedRecipe)
```
Comment (eduardoboucas) [inline dadi/lib/models/route.js]: Do you mind just changing this to:

```js
if (cachedRecipe) return cachedRecipe
```

That `Promise.resolve()` is unnecessary, as we're already inside a Promise.

Other than that, looks great!
